# https://github.com/audiolize/vagrant-softlayer
# vagrant plugin install vagrant-softlayer
# vagrant up --provider=softlayer


############### WHERE IS THE BOX!!!?!?!?!?

############## You need to make it!! Please follow https://github.com/audiolize/vagrant-softlayer/tree/master/example_box
############## which is an example to the most basic box ever..


require_relative '../util/util'

CONFIG_FILE = ENV['CONFIG_FILE'] # supports JSON!!!

config = Util.new
cloudname = File.basename(Dir.getwd)
configs = config.getConfigs(CONFIG_FILE, cloudname)

environment_provision_script = config.initEnvironmentProvision(configs)

excludes_array = ['.git','_site']
config.setVagrantignore(excludes_array)


Vagrant.configure("2") do |config|

  config.vm.box = "softlayer-box"
  # config.vm.box_url = "THERE IS NO SUCH BOX AT THE MOMENT OF WRITING IT!!!"

  config.vm.provision "shell", inline: environment_provision_script

  config.vm.provision "shell" do |s|
    s.path = "../provision.sh"
    s.privileged = false
  end

  config.vm.provider :softlayer do |sl|
    sl.api_key  = configs['softlayer']['apiKey']
    sl.username = configs['softlayer']['username']
    sl.ssh_key  = configs['softlayer']['sshKey']

    sl.vm.synced_folder "../synced_folder", type: "rsync", rsync__exclude: excludes_array





  end
end
