# https://github.com/mitchellh/vagrant-aws
# vagrant plugin install vagrant-aws
# vagrant up --provider=aws



require 'yaml'
CONFIG_FILE = ENV['CONFIG_FILE'] # supports JSON!!!!

unless CONFIG_FILE
  abort("\n\n\n\nMUST DEFINE VARIABLE `CONFIG_FILE` TO POINT TO JSON OR YAML CONFIGURATION. see `defaults.json` file for configuration example\n\n\n")
end

defaults = YAML.load_file("#{File.dirname(File.expand_path(__FILE__))}/defaults.json")
configs = YAML.load_file("#{CONFIG_FILE}")

# http://stackoverflow.com/a/9381776/1068746
class ::Hash
  def deep_merge(second)
    merger = proc { |key, v1, v2| Hash === v1 && Hash === v2 ? v1.merge(v2, &merger) : v2 }
    self.merge(second, &merger)
  end
end


configs = defaults.deep_merge(configs)

environment_provision_script = "echo \""

if configs.has_key?("environmentVariables")
  configs['environmentVariables'].each { |k, v|  environment_provision_script = environment_provision_script + "#{k}=\\\"#{v}\\\";\n" }
end

environment_provision_script = environment_provision_script + "\" > /vagrant/ENVIRONMENT_VARIABLES.sh"



Vagrant.configure("2") do |config|

  config.vm.synced_folder "../synced_folder", "/vagrant"

  config.vm.provision "shell", inline: environment_provision_script

  config.vm.provision "shell" do |s|

    s.path = "../provision.sh"
    s.privileged = false
  end

  #config.ssh.port = 22

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

  config.vm.provider :docker do |docker, override|
    docker.build_dir = configs['docker']['buildDir']
    docker.has_ssh = true
  end
end
