# https://github.com/tknerr/vagrant-managed-servers
# vagrant plugin install vagrant-managed-servers
# vagrant up


require_relative '../util/util'

CONFIG_FILE = ENV['CONFIG_FILE'] # supports JSON!!!

config = Util.new
cloudname = File.basename(Dir.getwd)
configs = config.getConfigs(CONFIG_FILE, cloudname)

environment_provision_script = config.initEnvironmentProvision(configs)

excludes_array = ['.git','_site']
config.setVagrantignore(excludes_array)

Vagrant.configure("2") do |config|

  config.vm.box = "tknerr/managed-server-dummy"

  config.vm.synced_folder "../synced_folder", "/vagrant", type: "rsync", rsync__exclude: excludes_array

  config.vm.provision "shell", inline: environment_provision_script

  config.vm.provision "shell" do |s|
    s.path = "../provision.sh"
    s.privileged = false
  end

  config.vm.provider :managed do |managed, override|
    managed.server = configs['managed']['server']
    override.ssh.username = configs['managed']['ssh']['username']
    override.ssh.private_key_path = configs['managed']['ssh']['privateKeyPath']
  end

end
