# https://github.com/cloudbau/vagrant-openstack-plugin.git
# vagrant plugin install vagrant-openstack-provider
# vagrant up --provider=openstack

require_relative '../util/util'

CONFIG_FILE = ENV['CONFIG_FILE'] # supports JSON!!!

config = Util.new
cloudname = File.basename(Dir.getwd)
configs = config.getConfigs(CONFIG_FILE, cloudname)

environment_provision_script = config.initEnvironmentProvision(configs)

excludes_array = ['.git','_site']
config.setVagrantignore(excludes_array)

Vagrant.configure("2") do |config|

  config.vm.box = "openstack-box"
  config.vm.box_url = "https://github.com/cloudbau/vagrant-openstack-plugin/raw/master/dummy.box"
  config.vm.synced_folder "../synced_folder", "/vagrant", type: "rsync", rsync__exclude: excludes_array
  config.vm.provision "shell", inline: environment_provision_script
  config.vm.provision "shell" do |s|
    s.path = "../provision.sh"
    s.privileged = false
  end

  config.vm.provider :openstack do |openstack|
    openstack.openstack_auth_url  = configs['openstack']['openstack_auth_url']
    openstack.username  = configs['openstack']['username']
    openstack.password  = configs['openstack']['password']
    openstack.tenant_name  = configs['openstack']['tenant_name']
    openstack.flavor  = configs['openstack']['flavor']
    openstack.server_name = configs['openstack']['machineName']
    openstack.image  = configs['openstack']['image']
    openstack.floating_ip_pool  = configs['openstack']['floating_ip_pool']
    config.ssh.username = configs['openstack']['ssh']['username']
    config.ssh.private_key_path = configs['openstack']['ssh']['private_key_path']
    openstack.keypair_name = configs['openstack']['keypair_name']
    openstack.networks = configs['openstack']['networks']

  end

  end


